c_compiler:
  - clang              # [unix]
  - clang-cl           # [win]
cxx_compiler:
  - clangxx            # [win]
  - clang-cl           # [win]
c_compiler_version:
  - 19
cxx_compiler_version:
  - 19
c_stdlib_version:      # [linux]
  - 2.28               # [linux]
