{% set version = "2.3.6" %}

package:
  name: deno
  version: {{ version }}

source:
  - url: https://github.com/denoland/deno/releases/download/v{{ version }}/deno_src.tar.gz
    sha256: 48a03e4fecd14ae1a17374cec387458b57c55bcdc3090894385815f9f9d84331
    patches:   # [win]
      - 01-fix-libffi-msvc.patch     # [win]
  - url: https://github.com/denoland/deno/releases/download/v{{ version }}/deno-aarch64-unknown-linux-gnu.zip  # [linux and aarch64]
    sha256: 2f3d086d42e1be40457dd738c660f68cabe26a2a7005d3c8d53a3cb221118f61  # [linux and aarch64]
    folder: release-build  # [linux and aarch64]
  - url: https://github.com/denoland/deno/releases/download/v{{ version }}/deno-aarch64-apple-darwin.zip  # [osx and arm64]
    sha256: 2d539dd5df70f0195bd51b746fd7696f74fdd401e32a4b2f51c0901ed295015e  # [osx and arm64]
    folder: release-build  # [osx and arm64]

build:
  number: 0

requirements:
  build:
    - {{ compiler("rust") }}
    # needs c compiler for run_exports
    - {{ compiler("c") }}   # [not osx or not arm64]
    - {{ stdlib("c") }}     # [not osx or not arm64]
    - cmake    # [win]
    # for some reason, test_ffi pkg needs lld on osx-arm64
    # - lld    # [osx and arm64]
    - cargo-bundle-licenses
    - make   # [unix and not arm64]
    - cmake  # [unix and not arm64]  
    - libclang     # [linux and x86_64]
    - llvmdev      # [linux and x86_64]
    # libprotobuf is on build, not host, since we only need protoc
    - libprotobuf
  # cross-builds also need host libgcc to run the cross-built files
  host:
    - libgcc    # [linux and aarch64]
    - zlib  # [not aarch64]
  run:   # [osx and x86_64]

test:
  files:
    - test-build-arch.js
  commands:
    - deno --help
    - deno run https://docs.deno.com/examples/scripts/hello_world.ts
    - if [ "$DENO_INSTALL_ROOT" != "$PREFIX" ]; then echo "DENO_INTALL_ROOT var not set correctly" && exit 1; fi    # [unix]
    - IF "%DENO_INSTALL_ROOT:/=\%" NEQ "%PREFIX:/=\%\Library" exit 1    # [win]
    - deno run test-build-arch.js

about:
  home: https://deno.land
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.md
    - DENO_THIRDPARTY_LICENSES.yml
  summary: A simple, modern and secure runtime for JavaScript and TypeScript that uses V8 and is built in Rust
  doc_url: https://deno.land/manual
  dev_url: https://github.com/denoland/deno

extra:
  recipe-maintainers:
    - mdekstrand
    - cderv
    - cscheid
    - dragonstyle
    - msarahan
