{% set version = "1.17.3" %}

package:
  name: deno
  version: {{ version }}

source:
  - url: https://github.com/denoland/deno/releases/download/v{{ version }}/deno_src.tar.gz
    sha256: 1404a59d06fbf424062af39a76216f6e181ca7c5876e3431768f8266ad4000a6

build:
  number: 0
  missing_dso_whitelist:
    # As mentioned below, we fall back to the system compilers on MacOS, because the conda-forge
    # clang compilers do not provide Metal support. This Metal framework might be good to add to
    # conda-build's default list of missing_dso_whitelist
    - /System/Library/Frameworks/Metal.framework/Versions/A/Metal  # [osx]

requirements:
  build:
    # use XCode compilers on MacOS because we need Metal
    - {{ compiler("c") }}      # [not osx]
    - {{ compiler("cxx") }}    # [not osx]
    - cargo-bundle-licenses
    - make   # [unix]
    - rust

test:
  commands:
    - deno --help

about:
  home: https://deno.land
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.md
    - DENO_THIRDPARTY_LICENSES.yml
  summary: A simple, modern and secure runtime for JavaScript and TypeScript that uses V8 and is built in Rust
  doc_url: https://deno.land/manual
  dev_url: https://github.com/denoland/deno

extra:
  recipe-maintainers:
    - msarahan
