{% set version = "1.38.2" %}

package:
  name: deno
  version: {{ version }}

source:
  - url: https://github.com/denoland/deno/releases/download/v{{ version }}/deno_src.tar.gz  # [not osx or not arm64]
    sha256: 9d2a241c8b1ee203ac49824dd7410dd7c8dc82599d2a62d704fd8a7a46abebc5  # [not osx or not arm64]
    patches:   # [not osx or not arm64]
      - 01-fix-libffi-msvc.patch     # [not osx or not arm64]
      - 02-cross-build-source.patch   # [not osx or not arm64]
      - 03-update-ring-version.patch  # [not osx or not arm64]
  - url: https://github.com/denoland/deno/releases/download/v{{ version }}/deno-aarch64-apple-darwin.zip  # [osx and arm64]
    sha256: aabb6bd9d9fb3b67a20f70787f04c7fbc5d81a91ebecfad8a11aaecaed5d5826  # [osx and arm64]

build:
  number: 0

requirements:   # [not osx or not arm64]
  build:   # [not osx or not arm64]
    - {{ compiler("rust") }}   # [not osx or not arm64]
    # needs c compiler for run_exports
    - {{ compiler("c") }}      # [not osx or not arm64]
    # for some reason, test_ffi pkg needs lld on osx-arm64
    # - lld    # [osx and arm64]
    - cargo-bundle-licenses   # [not osx or not arm64]
    - make   # [unix and not arm64]
    - cmake  # [unix and not arm64]
    # libprotobuf is on build, not host, since we only need protoc
    - libprotobuf  # [not osx or not arm64]
  run:   # [osx and x86_64]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET }}  # [osx and x86_64]

test:
  commands:
    - deno --help
    - deno run https://examples.deno.land/hello-world.ts
    - if [ "$DENO_INSTALL_ROOT" != "$PREFIX" ]; then echo "DENO_INTALL_ROOT var not set correctly" && exit 1; fi    # [unix]
    - IF "%DENO_INSTALL_ROOT:/=\%" NEQ "%PREFIX:/=\%\Library" exit 1    # [win]

about:
  home: https://deno.land
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.md    # [not osx or not arm64]
    - DENO_THIRDPARTY_LICENSES.yml    # [not osx or not arm64]
    # the binary doesn't ship with a license. This is one taken from the github repo.
    - LICENSE    # [osx and arm64]
  summary: A simple, modern and secure runtime for JavaScript and TypeScript that uses V8 and is built in Rust
  doc_url: https://deno.land/manual
  dev_url: https://github.com/denoland/deno

extra:
  recipe-maintainers:
    - mdekstrand
    - cderv
    - cscheid
    - dragonstyle
    - msarahan
